### ISSUE TITLE
更新後遊戲打不開

### ISSUE THREAD

**Issue by KingkazmaSola** [HIllya51/LunaTranslator#1079]
### Question 问题

現在更新後遊戲打不開

**Comment by KingkazmaSola** [comment]
https://github.com/user-attachments/assets/4b14fd3d-fbdd-4a4f-ae6d-571d8467d3c4

**Comment by HIllya51** [comment]
给我log。

**Comment by KingkazmaSola** [comment]
Traceback (most recent call last):
  File "D:\Game\LunaTranslator\LunaTranslator\LunaTranslator.py", line 764, in starthira
    self.hira_ = _hira(name)
  File "D:\Game\LunaTranslator\LunaTranslator\hiraparse\basehira.py", line 22, in __init__
    self.init()
  File "D:\Game\LunaTranslator\LunaTranslator\hiraparse\mecab.py", line 76, in init
    raise Exception("no exits " + mecabpath)
Exception: no exits

**Comment by HIllya51** [comment]
...这log没用。那你把userconfig打包给我看一下

**Comment by KingkazmaSola** [comment]
https://drive.google.com/file/d/11LpsOpZ1hEjbLi7Wr_NsUkWKFobQDiey/view?usp=sharing
