### ISSUE TITLE
Jitendex fails

### ISSUE THREAD

**Issue by yuukibarns** [HIllya51/LunaTranslator#1271]
### Version 程序版本

v6.16.6

### OS version and bits 系统版本和位数

windows 10

### bug's screenshot 错误截图

```
Mesa: SVGA3D; build: RELEASE;

Mesa: 24.0.2
Traceback (most recent call last):
  File "./LunaTranslator\cishu\mdict.py", line 2464, in searchthread
    set(self.searchthread_internal(index, k, __safe))
  File "./LunaTranslator\cishu\mdict.py", line 2446, in searchthread_internal
    for content in index.mdx_lookup(k):
  File "./LunaTranslator\cishu\mdict.py", line 2006, in mdx_lookup
    lookup_result_list.append(self.get_mdx_by_index(mdx_file, index))
  File "./LunaTranslator\cishu\mdict.py", line 1966, in get_mdx_by_index
    data = self.get_data_by_index(fmdx, index)
  File "./LunaTranslator\cishu\mdict.py", line 1957, in get_data_by_index
    _record_block = zlib.decompress(record_block_compressed[8:])
zlib.error: Error -3 while decompressing data: incorrect header check
```

### Reproduction steps 复现步骤

MDict设置为到mdx文件路径，查词发现没有MDict，debug信息如上

**Comment by HIllya51** [comment]
你的文件有问题吧？你查的哪个词？文件发出来看看？

**Comment by HIllya51** [comment]
你重下一下最新的mdx和mdd文件吧，你这看起来文件是损坏的，我测试是没问题的。
![屏幕截图 2024-12-31 002222](https://github.com/user-attachments/assets/81bca153-ec63-40df-aa9e-1c6e6f6ded25)

**Comment by yuukibarns** [comment]
Jitendex是最新的。
更新之后左边多了一个按钮，里面可以看到Jitendex的目录，但界面里还是没有Jitendex
![Screenshot_20241231_083922](https://github.com/user-attachments/assets/7851aab6-4a88-491f-94dc-9840462f0245)

**Comment by HIllya51** [comment]
你把你的词典文件打包给我。
