### ISSUE TITLE
编译源码安装依赖时PyQt报错

### ISSUE THREAD

**Issue by luojunyuan** [HIllya51/LunaTranslator#215]
`pip install -r requirements.txt`

```
Collecting PyQt5==5.15.7
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "C:\Users\kimika\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\kimika\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kimika\AppData\Local\Programs\Python\Python311-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kimika\AppData\Local\Temp\pip-build-env-kfv6_ry9\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kimika\AppData\Local\Temp\pip-build-env-kfv6_ry9\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\kimika\AppData\Local\Temp\pip-build-env-kfv6_ry9\overlay\Lib\site-packages\sipbuild\project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\kimika\AppData\Local\Temp\pip-install-blu914nd\pyqt5_0fd9e4e47e234597ae22ce8bf6a4578b\project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\kimika\AppData\Local\Temp\pip-build-env-kfv6_ry9\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\kimika\AppData\Local\Temp\pip-build-env-kfv6_ry9\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\kimika\AppData\Local\Temp\pip-build-env-kfv6_ry9\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by HIllya51** [comment]
用Python3.8
