### ISSUE TITLE
自定义python处理文本失败

### ISSUE THREAD

**Issue by jeshs** [HIllya51/LunaTranslator#615]
1、hook到游戏的原文如下。希望删掉包含（z）的行
```
(z)END 4 / 4 →(x)4月 第1週 日曜日 昼 　／ 幻影切替可能(c) ／ 目的地:なし
あれ？

(z)← 1 / 4 　   4月 第1週 日曜日 昼 　／ 幻影切替可能(c) ／ 目的地:なし
君は、この前会ったよね？

(z)← 2 / 4 →(x)4月 第1週 日曜日 昼 　／ 幻影切替可能(c) ／ 目的地:なし
よく会うけど、この辺りに住んでるの？

(z)← 3 / 4 →(x)4月 第1週 日曜日 昼 　／ 幻影切替可能(c) ／ 目的地:なし
```
2、自定义python代码如下
```
def POSTSOLVE(line): 
    # 检查每一行是否包含 'z' 
    if "z" in line:
        return ""  # 返回空字符串（即删除该行）
    else:
        return line  # 否则，返回原始行内容
```
3、结果没有任何文本输出，应该没有调任何翻译接口。是我哪里弄错了吗

**Comment by HIllya51** [comment]
<img width="811" alt="屏幕截图 2024-03-28 153837" src="https://github.com/HIllya51/LunaTranslator/assets/101191390/295d46f9-d1ab-46b6-a6a4-4505964add09">

看控制台

**Comment by jeshs** [comment]
索引越界了
```
  File "D:\Portable\LunaTranslator\LunaTranslator\myutils\post.py", line 327, in POSTSOLVE
  File "D:\Portable\LunaTranslator\LunaTranslator\myutils\post.py", line 58, in _3_f
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "D:\Portable\LunaTranslator\LunaTranslator\myutils\post.py", line 325, in POSTSOLVE
  File "D:\Portable\LunaTranslator\LunaTranslator\myutils\post.py", line 108, in _10_f
IndexError: list index out of range
Traceback (most recent call last):
  File "D:\Portable\LunaTranslator\LunaTranslator\myutils\post.py", line 325, in POSTSOLVE
  File "D:\Portable\LunaTranslator\LunaTranslator\myutils\post.py", line 130, in _13_f
IndexError: list index out of range
```

<img width="785" alt="image" src="https://github.com/HIllya51/LunaTranslator/assets/43285002/6248c6e9-b671-4e53-bc50-962645f13536">

**Comment by jeshs** [comment]
这个问题的原因是 POSTSOLVE 函数的参数是将多个行作为参数传递的。我自己处理了。不过为了使用方便，可以考虑改一下这个函数，让用户只需要处理一行，调用时加个循环。我是这样写的
```
def POSTSOLVE(input_text): 
    keyword = '(z)'
    # 将输入字符串分割成单独的行
    lines = input_text.split('\n')
    # 进行列表推导，只保留不包含关键字的行
    filtered_lines = [line for line in lines if keyword not in line]
    # 将过滤后的字符串重新连接成一个字符串并返回
    return '\n'.join(filtered_lines)
```

**Comment by HIllya51** [comment]
所以到底是什么bug
