### ISSUE TITLE
点击确定前往下载 QWebEngine 不起作用（wine）

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#939]
### Version 程序版本

5.15.12

### bug's screenshot 错误截图

```py
Traceback (most recent call last):
  File "C:\LunaTranslator_x86\LunaTranslator\gui\usefulwidget.py", line 671, in comboboxcallbackwrap
    call(_)
  File "C:\LunaTranslator_x86\LunaTranslator\gui\setting_display_text.py", line 241, in resetgroudswitchcallback
    on_not_find_qweb(self)
  File "C:\LunaTranslator_x86\LunaTranslator\gui\setting_display_text.py", line 227, in on_not_find_qweb
    okcallback=_okcallback,
  File "C:\LunaTranslator_x86\LunaTranslator\gui\usefulwidget.py", line 141, in getQMessageBox
    okcallback()
  File "C:\LunaTranslator_x86\LunaTranslator\gui\setting_display_text.py", line 218, in _okcallback
    os.startfile(link)
FileNotFoundError: [WinError 3] 找不到路径。: 'https://lunatranslator.xyz/Resource/QWebEngine_x86.zip'
```

### Reproduction steps 复现步骤

![image](https://github.com/user-attachments/assets/18829582-c8bc-49be-9284-c743cf438fa2)

![image](https://github.com/user-attachments/assets/9a93b87a-65a0-4b4a-966f-1a9eee0e1e64)

点 OK, 控制台提示错误，软件本体无反应。

**Comment by asukaminato0721** [comment]
发现是 win32 特有的 feature, <https://stackoverflow.com/questions/4216985/call-to-operating-system-to-open-url> , 可能 wine 没做到兼容这层？

**Comment by asukaminato0721** [comment]
经测试 qwebengine qt5 会让整个设置界面都打不开，如果调了那个，去 userconfig 把 `rendertext_using` 删掉就恢复了。

**Comment by HIllya51** [comment]
https://github.com/HIllya51/LunaTranslator/commit/480dc6b049d35e4545ee76f3cb5f18e7bd809f11

**Comment by HIllya51** [comment]
wine的shellexeute没实现打开链接的缘故。改成了判断是wine环境则弹个窗把链接显示出来这样子。
